export const CANDIDATE_DATA_REQUEST= 'DATA_REQUEST';
export const CANDIDATE_DATA_SUCCESS= 'DATA_SUCCESS';
export const CANDIDATE_DATA_ERROR = 'DATA_ERROR';

export const ADMIN_DASHBOARD_DATA_REQUEST = 'ADMIN_DASHBOARD_DATA_REQUEST'
export const ADMIN_DASHBOARD_DATA_SUCCESS = 'ADMIN_DASHBOARD_DATA_SUCCESS'
export const ADMIN_DASHBOARD_DATA_ERROR = 'ADMIN_DASHBOARD_DATA_ERROR'
