

export const candidates = [
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Chemical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Chemical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Chemical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Chemical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },{
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Masters",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Bachelors",
        'education_title': "Chemical Engineering",
        'gender': "female",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    },
    {
        'education_level': "Secondary School Certificate",
        'education_title': "ELectrical Engineering",
        'gender': "male",
        'location': "Lahore",
        "name": "THe  Name",
        "title": "Electrical Engineer",
        "user_id": "641b1ed4866724e2a34da377",
    }
]