export const LOADING_TRUE = 'LOADING_TRUE'
export const LOADING_FALSE = 'LOADING_FALSE'

export const CERTIFICATE_DATA_REQUEST='CERTIFICATE_DATA_REQUEST';
export const CERTIFICATE_DATA_SUCCESS='CERTIFICATE_DATA_SUCCESS';
export const CERTIFICATE_DATA_FAILED = 'CERTIFICATE_DATA_FAILED';

export const CV_BUILDER_REQUEST='CV_BUILDER_REQUEST';
export const CV_BUILDER_SUCCESS='CV_BUILDER_SUCCESS';
export const CV_BUILDER_FAILED='CV_BUILDER_FAILED';

export const VIEW_OFFER_REQUEST= 'VIEW_OFFER_REQUEST';
export const VIEW_OFFER_SUCCESS= 'VIEW_OFFER_SUCCESS';
export const VIEW_OFFER_FAILED= 'VIEW_OFFER_FAILED';


export const LOGOUT_REQUEST= 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS= 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED= 'LOGOUT_FAILD';