export const SAVE_PROFILE_DATA_REQUESET = 'SAVE_PROFILE_DATA_REQUESET'
export const SAVE_PROFILE_DATA_ERROR = 'SAVE_PROFILE_DATA_ERROR'
export const SAVE_PROFILE_DATA_SUCCESS = 'SAVE_PROFILE_DATA_SUCCESS'


export const GET_PROFILE_DATA_REQUESET = 'GET_PROFILE_DATA_REQUESET'
export const GET_PROFILE_DATA_ERROR = 'GET_PROFILE_DATA_ERROR'
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS'
