export const SAVE_PROFILE_DATA_REQUESET = 'SAVE_PROFILE_DATA_REQUESET'
export const SAVE_PROFILE_DATA_ERROR = 'SAVE_PROFILE_DATA_ERROR'
export const SAVE_PROFILE_DATA_SUCCESS = 'SAVE_PROFILE_DATA_SUCCESS'


export const GET_PROFILE_DATA_REQUESET = 'GET_PROFILE_DATA_REQUESET'
export const GET_PROFILE_DATA_ERROR = 'GET_PROFILE_DATA_ERROR'
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS'

export const GET_CANDIDATES_REQUESET = 'GET_CANDIDATES_REQUESET'
export const GET_CANDIDATES_ERROR = 'GET_CANDIDATES_ERROR'
export const GET_CANDIDATES_SUCCESS = 'GET_CANDIDATES_SUCCESS'

export const SELECT_CANDIDATES = 'SELECT_CANDIDATES'
export const REMOVE_CANDIDATES = 'REMOVE_CANDIDATES'

export const SEND_OFFER_REQUESET = 'SEND_OFFER_REQUESET'
export const SEND_OFFER_ERROR = 'SEND_OFFER_ERROR'
export const SEND_OFFER_SUCCESS = 'SEND_OFFER_SUCCESS'


