export const SEND_PROFILE_PICTURE_REQUEST = 'SEND_PROFILE_PICTURE_REQUEST'
export const SEND_PROFILE_PICTURE_SUCCESS = 'SEND_PROFILE_PICTURE_SUCCESS'
export const SEND_PROFILE_PICTURE_ERROR = 'SEND_PROFILE_PICTURE_ERROR'


export const SEND_PERSONAL_INFO_REQUEST = 'SEND_PERSONAL_INFO_REQUEST'
export const SEND_PERSONAL_INFO_SUCCESS = 'SEND_PERSONAL_INFO_SUCCESS'
export const SEND_PERSONAL_INFO_ERROR = 'SEND_PERSONAL_INFO_ERROR'


export const GET_PERSONAL_INFO_REQUEST = 'GET_PERSONAL_INFO_REQUEST'
export const GET_PERSONAL_INFO_SUCCESS = 'GET_PERSONAL_INFO_SUCCESS'
export const GET_PERSONAL_INFO_ERROR = 'GET_PERSONAL_INFO_ERROR'

export const SEND_EDUCATION_INFO_REQUEST = 'SEND_EDUCATION_INFO_REQUEST'
export const SEND_EDUCATION_INFO_SUCCESS = 'SEND_EDUCATION_INFO_SUCCESS'
export const SEND_EDUCATION_INFO_ERROR = 'SEND_EDUCATION_INFO_ERROR'


export const GET_EDUCATION_INFO_REQUEST = 'GET_EDUCATION_INFO_REQUEST'
export const GET_EDUCATION_INFO_SUCCESS = 'GET_EDUCATION_INFO_SUCCESS'
export const GET_EDUCATION_INFO_ERROR = 'GET_EDUCATION_INFO_ERROR'


export const SEND_EXPERIENCE_INFO_REQUEST = 'SEND_EXPERIENCE_INFO_REQUEST'
export const SEND_EXPERIENCE_INFO_SUCCESS = 'SEND_EXPERIENCE_INFO_SUCCESS'
export const SEND_EXPERIENCE_INFO_ERROR = 'SEND_EXPERIENCE_INFO_ERROR'


export const GET_EXPERIENCE_INFO_REQUEST = 'GET_EXPERIENCE_INFO_REQUEST'
export const GET_EXPERIENCE_INFO_SUCCESS = 'GET_EXPERIENCE_INFO_SUCCESS'
export const GET_EXPERIENCE_INFO_ERROR = 'GET_EXPERIENCE_INFO_ERROR'


export const SEND_SKILLS_INFO_REQUEST = 'SEND_SKILLS_INFO_REQUEST'
export const SEND_SKILLS_INFO_SUCCESS = 'SEND_SKILLS_INFO_SUCCESS'
export const SEND_SKILLS_INFO_ERROR = 'SEND_SKILLS_INFO_ERROR'


export const GET_SKILLS_INFO_REQUEST = 'GET_SKILLS_INFO_REQUEST'
export const GET_SKILLS_INFO_SUCCESS = 'GET_SKILLS_INFO_SUCCESS'
export const GET_SKILLS_INFO_ERROR = 'GET_SKILLS_INFO_ERROR'


export const SEND_ABOUT_INFO_REQUEST = 'SEND_ABOUT_INFO_REQUEST'
export const SEND_ABOUT_INFO_SUCCESS = 'SEND_ABOUT_INFO_SUCCESS'
export const SEND_ABOUT_INFO_ERROR = 'SEND_ABOUT_INFO_ERROR'


export const GET_ABOUT_INFO_REQUEST = 'GET_ABOUT_INFO_REQUEST'
export const GET_ABOUT_INFO_SUCCESS = 'GET_ABOUT_INFO_SUCCESS'
export const GET_ABOUT_INFO_ERROR = 'GET_ABOUT_INFO_ERROR'