export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";


export const VERIFICATION_REQUEST = "VERIFICATION_REQUEST";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_ERROR = "VERIFICATION_ERROR";


export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_SUCCESS = "OTP_SUCCESS";
export const OTP_ERROR = "OTP_ERROR";

export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_ERROR = 'SEND_EMAIL_ERROR';

export const RESENEND_VERIFICATION_EMAIL_REQUEST = "RESEND_VERIFICATION_EMAIL_REQUEST";
export const RESENEND_VERIFICATION_EMAIL_SUCCESS = "RESEND_VERIFICATION_EMAIL_SUCCESS";
export const RESENEND_VERIFICATION_EMAIL_ERROR = "RESEND_VERIFICATION_EMAIL_ERROR";

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS= 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR= 'RESET_PASSWORD_FAILED';


export const REQUEST_TOKENS_REQUEST = 'REQUEST_TOKENS_REQUEST';
export const REQUEST_TOKENS_SUCCESS= 'REQUEST_TOKENS_SUCCESS';
export const REQUEST_TOKENS_ERROR= 'REQUEST_TOKENS_FAILED';